githubUser: "sad1ee"

packages:
  arch:
    yay:
      - "git"
      - "curl"
      - "zsh"
      - "unzip"
      - "zinit"
      - "nvim"
      - "bat"
      - "fzf"
      - "oh-my-posh-bin"
      - "zoxide"
      - "tmux"
      - "tmux-plugin-manager"
      - "btop"
      - "fastfetch"
      - "lsd"
      - "yazi"
      - "ffmpeg"
      - "7zip"
      - "jq"
      - "poppler"
      - "fd"
      - "ripgrep"
      - "resvg"
      - "imagemagick"
      - "man-db"
      - "man-pages"
      - "age"
      - "fwupd"
      - "powertop"
      - "speedtest-cli"
      - "chezmoi"
  ubuntu:
    apt:
      - "git"
      - "curl"
      - "unzip"
      - "fd-find"
      - "ripgrep"
      - "ranger"
      - "zsh"
      - "bat"
      - "fzf"
      - "zoxide"
      - "tmux"
      - "tmux-plugin-manager"
      - "btop"
      - "fastfetch"
      - "lsd"
      - "age"
      - "fwupd"
      - "powertop"
      - "speedtest-cli"
      - "fastfetch"
