[[manager.prepend_keymap]]
on = "<S-t>"
run = "close"

[[manager.prepend_keymap]]
on = "<S-h>"
run = "tab_switch -1 --relative"

[[manager.prepend_keymap]]
on = "<S-l>"
run = "tab_switch 1 --relative"
