-- return {
--   -- 1) Mason: ensure pyright, black, flake8 are installed
--   {
--     "williamboman/mason.nvim",
--     opts = function(_, opts)
--       vim.list_extend(opts.ensure_installed, { "pyright", "black", "flake8" })
--     end,
--   },
--
--   -- 2) Null-LS: add Black formatter + Flake8 diagnostics
--   {
--     "jose-elias-alvarez/null-ls.nvim",
--     opts = function(_, opts)
--       local nls = require("null-ls")
--       opts.sources = opts.sources or {}
--       vim.list_extend(opts.sources, {
--         nls.builtins.formatting.black.with({ extra_args = { "--line-length=88" } }),
--         nls.builtins.diagnostics.flake8,
--       })
--     end,
--   },
--
--   -- 3) nvim-lspconfig: configure Pyright for strict type checking
--   {
--     "neovim/nvim-lspconfig",
--     opts = function(_, opts)
--       opts.servers = opts.servers or {}
--       opts.servers.pyright = {
--         settings = {
--           python = {
--             analysis = {
--               typeCheckingMode = "strict",
--               diagnosticMode = "workspace",
--             },
--           },
--         },
--       }
--     end,
--   },
-- }
